import {
  Star,
  Utensils,
  Mountain,
  Palette,
  Music,
  Camera,
  Heart,
} from 'lucide-react';

export const categories = [
  { id: 'all', name: 'All', icon: Star },
  { id: 'food', name: 'Food & Drink', icon: Utensils },
  { id: 'adventure', name: 'Adventure', icon: Mountain },
  { id: 'art', name: 'Art & Culture', icon: Palette },
  { id: 'music', name: 'Music', icon: Music },
  { id: 'photography', name: 'Photography', icon: Camera },
  { id: 'wellness', name: 'Wellness', icon: Heart },
];

const experienceReviewTemplates = [
  { rating: 5, comment: 'The host was energetic and made the whole session very engaging.' },
  { rating: 5, comment: 'Clear instructions, friendly vibe, and a truly memorable local experience.' },
  { rating: 4, comment: 'Great activity overall. Well organized and worth the time.' },
  { rating: 5, comment: 'Loved every part of this experience. Highly recommended for first-timers.' },
  { rating: 4, comment: 'Good pacing and great storytelling from the host throughout the session.' },
  { rating: 5, comment: 'Fantastic value and authentic atmosphere. Would do this again.' },
  { rating: 5, comment: 'One of the highlights of our trip. Professional and very welcoming host.' },
  { rating: 4, comment: 'Enjoyable and informative. The location and flow were both excellent.' },
  { rating: 5, comment: 'Perfect mix of fun and learning. We left with great memories.' },
  { rating: 5, comment: 'Super smooth experience with thoughtful details at every step.' },
];

const buildExperienceReviews = (hostName, city) =>
  experienceReviewTemplates.map((template, index) => ({
    id: `${hostName.toLowerCase()}-${city.toLowerCase()}-${index + 1}`,
    reviewer: `Guest ${index + 1}`,
    rating: template.rating,
    comment: `${template.comment} (${city})`,
    date: `2026-03-${String(10 + index).padStart(2, '0')}`,
  }));

export const sampleExperiences = [
  {
    _id: '1',
    title: 'Traditional Indian Cooking Class',
    category: 'food',
    host: { firstName: 'Priya', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200' },
    location: { city: 'Mumbai', country: 'India' },
    duration: 180,
    price: 2500,
    rating: { average: 4.9, count: 234 },
    image: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800',
    description: 'Learn to cook authentic Indian dishes with a local chef in their home kitchen.',
    maxGuests: 8,
    languages: ['English', 'Hindi'],
    reviews: buildExperienceReviews('Priya', 'Mumbai'),
  },
  {
    _id: '2',
    title: 'Himalayan Trek Adventure',
    category: 'adventure',
    host: { firstName: 'Raj', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200' },
    location: { city: 'Manali', country: 'India' },
    duration: 480,
    price: 3500,
    rating: { average: 4.8, count: 156 },
    image: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800',
    description: 'Experience the breathtaking beauty of the Himalayas with an expert guide.',
    maxGuests: 12,
    languages: ['English'],
    reviews: buildExperienceReviews('Raj', 'Manali'),
  },
  {
    _id: '3',
    title: 'Street Art Walking Tour',
    category: 'art',
    host: { firstName: 'Ananya', avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200' },
    location: { city: 'Delhi', country: 'India' },
    duration: 120,
    price: 1500,
    rating: { average: 4.7, count: 89 },
    image: 'https://images.unsplash.com/photo-1561059488-916d69792237?w=800',
    description: 'Discover hidden street art gems and meet local artists in the vibrant streets.',
    maxGuests: 10,
    languages: ['English', 'Hindi'],
    reviews: buildExperienceReviews('Ananya', 'Delhi'),
  },
  {
    _id: '4',
    title: 'Classical Music Session',
    category: 'music',
    host: { firstName: 'Vikram', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200' },
    location: { city: 'Varanasi', country: 'India' },
    duration: 150,
    price: 2000,
    rating: { average: 5.0, count: 67 },
    image: 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800',
    description: 'Immerse yourself in the spiritual sounds of Indian classical music.',
    maxGuests: 6,
    languages: ['English', 'Hindi'],
    reviews: buildExperienceReviews('Vikram', 'Varanasi'),
  },
  {
    _id: '5',
    title: 'Sunrise Photography Workshop',
    category: 'photography',
    host: { firstName: 'Maya', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200' },
    location: { city: 'Jaipur', country: 'India' },
    duration: 240,
    price: 2800,
    rating: { average: 4.9, count: 112 },
    image: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=800',
    description: 'Capture the golden light of sunrise over the Pink City with pro tips.',
    maxGuests: 8,
    languages: ['English'],
    reviews: buildExperienceReviews('Maya', 'Jaipur'),
  },
  {
    _id: '6',
    title: 'Yoga & Meditation Retreat',
    category: 'wellness',
    host: { firstName: 'Deepa', avatar: 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=200' },
    location: { city: 'Rishikesh', country: 'India' },
    duration: 300,
    price: 3000,
    rating: { average: 4.8, count: 198 },
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800',
    description: 'Find inner peace with authentic yoga practices by the Ganges.',
    maxGuests: 15,
    languages: ['English', 'Hindi', 'Sanskrit'],
    reviews: buildExperienceReviews('Deepa', 'Rishikesh'),
  },
];
